### ISSUE TITLE
switch bug when calling certain functions on one line

### ISSUE THREAD

**Issue by Kar2k** [Zeex/pawn#27] opened 2014-04-27 15:20 UTC
Briefly,

case 4: { showPoliceRefill(playerid, .refillType = 1); return 1; } 

works

but 

case 4: showPoliceRefill(playerid, .refillType = 1);

crashes the compiler (it reports 26 errors with the latest test binary)

showPoliceRefill(playerid); works fine but showPoliceRefill(playerid, .refillType = 1); doesn't

It crashes with a default function argument

#include <a_samp>

main()
{
    new playerid, option = 1;
    switch(option)
    {
	    case 1: showPoliceRefill(playerid, .refillType = 1);
    }
}

showPoliceRefill(playerid, refillType = 0)
{
	switch(refillType)
	{
	    case 0: functionex();
	    case 1: functionex();
	}
}

functionex()
{
	return 1;
}

EDIT: I can't get it recreated in a blank script, it happens in my large script. -.-

**Comment by Zeex** [comment] 2015-04-03 03:39
I could not reproduce this either.

Closing this for now. Feel free to reopen if you make a repro.

**Closed by Zeex** 2015-04-03 03:39 UTC
