### ISSUE TITLE
New Version include guard not working  properly with YSI

### ISSUE THREAD

**Issue by rt-2** [Zeex/pawn#164] opened 2017-03-31 17:47 UTC
Hello,
```
#include <YSI\y_iterate> //#include <foreach>
#include <YSI\y_iterate> //#include <foreach>
```
It compiled well with my old version of this compiler (Sorry I don't know which exactly), but when I tried upgrading today, I had an warning in YSI\y_iterate, basicly because it was included twice, there was a redefinition of constant.

Thank you,
rt-2

**Comment by Dayvison** [comment] 2017-03-31 20:03
What vesion of YSI? [Misiur/YSI-Includes](https://github.com/Misiur/YSI-Includes) works fine when i reproduce this.

**Comment by rt-2** [comment] 2017-04-06 19:22
I find it weird because I downloaded the new version of YSI and the new version of this compiler, and when I compile a blank gamemode with the include twice, I get the error:
``C:\Users\rt-2\Desktop\SAARP\SAMP\pawno\include\YSI\..\YSI_Data\y_iterate.inc(229) : warning 201: redefinition of constant/macro (symbol "_FOREACH_CUR_VERSION")``

**Comment by Y-Less** [comment] 2017-04-06 19:52
Ok, that is a problem - I'll look in to it,  `foreach` and `y_iterate` always had some strange include shenanigans to ensure that if you had both, the newer one was used regardless of which one you actually included.  Those are probably the cause, as the macros get very complex when different compiler behaviours are involved as well.

**Comment by rt-2** [comment] 2017-04-06 20:00
Yes the problem seems to come from this feature, that is where my own investigation pointed.
Just to be clear, in my test I haven't included <foreach>, I included <y_iterate> twice.
I think the real problem here is not the bug in y_iterate with that variable, my main concern is that already the 'include guard' should have already prevented a double include.

Thank you,
rt-2
P.S. Is there a option to disable the 'include guard'? Maybe I did that and I don't remember.

**Comment by Y-Less** [comment] 2017-04-06 20:05
Well no, that's what I mean by shenanigans - that include disables the guard for reasons.

**Comment by rt-2** [comment] 2017-04-06 20:06
Ok well, I guess there is only a bug in YSI now, I should post a issue on the appropriate github then..
I guess this one may be closed not sure

**Comment by Y-Less** [comment] 2017-04-25 09:10
Are you by any chance using this version (it was the only one I could get to reproduce this issue):

https://github.com/Open-GTO/foreach

See this message:

http://forum.sa-mp.com/showpost.php?p=3768059&postcount=53

They removed all the checks from the top of the stand-alone version that ensures this doesn't happen.  The problem is there, not YSI.

**Comment by rt-2** [comment] 2017-04-25 14:58
Ok but when I include YSI_Iterate twice I still get a new warning that wasn't there before.
The compiler have a 'include guard' that should prevent this but YSI disables it.
I'm just trying to find the solution for this new warning because it does happen in my script that Iterate will be included twice.
Yes I used this version of foreach but it doesn't matter because I don't want to use it anymore I'll just include YSI_Iterate in the future. I just wanted to demonstrate a bug, since YSI is supposed to detect the version of foreach and adapt to it,, but the real problem is Y_Iterate bugging with itself.
Thank you,
rt-2

**Comment by Y-Less** [comment] 2017-04-25 15:02
Yes, YSI is supposed to detect and adapt to foreach, the problem is that a recent version of the stand-alone include (not made by me) had this detection code removed - that is where the bug comes from.  To fix, change the header of y_iterate.inc to:

```pawn
// "y_iterate" is always higher than "foreach".
#define _Y_ITERATE_LOCAL_VERSION        42

#if __Pawn != 0x030A
	#define NO_CUSTOM_WARNINGS
#endif

// Foreach is testing us.
#if defined _FOREACH_INC_TEST
	#define _FOREACH_CUR_VERSION _Y_ITERATE_LOCAL_VERSION
	#endinput
#endif
#if !defined _FOREACH_NO_TEST
	#define _FOREACH_INC_TEST
	// Ignore the broken stand-alone version.
	#define _foreach_included
	#tryinclude <foreach>
	#undef _FOREACH_INC_TEST
	// <foreach> exists - test which is newer.
	#if defined _FOREACH_LOCAL_VERSION
		#if _FOREACH_LOCAL_VERSION > _Y_ITERATE_LOCAL_VERSION
			// Foreach is newer.
			#if defined _inc_foreach
				#undef _inc_foreach
			#endif
			#define _FOREACH_NO_TEST
			#include <foreach>
			#endinput
		#endif
	#elseif defined foreach
		#if __Pawn == 0x030A
			#define WARNING 1
			#include "y_iterate/warning" // Backwards-compatible directive.
			#endinput
		#else
			#error Old foreach.inc files are no longer compatible with YSI.
		#endif
	#endif
#endif
#define _FOREACH_INC_TEST
```

**Comment by rt-2** [comment] 2017-04-25 15:17
I changed the header and I still got ``C:\Users\rt-2\Desktop\SAARP\SAMP\pawno\include\YSI\..\YSI_Data\y_iterate.inc(229) : warning 201: redefinition of constant/macro (symbol "_FOREACH_CUR_VERSION")`` when I try to compile a file with only
```
#include <a_samp>
#include <YSI\y_iterate>
#include <YSI\y_iterate>
```
The problem seems to be this:
```
// Foreach is testing us.
#if defined _FOREACH_INC_TEST
	#define _FOREACH_CUR_VERSION _Y_ITERATE_LOCAL_VERSION
	#endinput
#endif
```
shouldn't be like this?
```
// Foreach is testing us.
#if defined _FOREACH_INC_TEST
	#undef _FOREACH_CUR_VERSION
	#define _FOREACH_CUR_VERSION _Y_ITERATE_LOCAL_VERSION
	#endinput
#endif
```

**Comment by Y-Less** [comment] 2017-04-25 15:30
I'm still not getting that, and I've tried every combination of includes and compilers I can think of.

**Comment by Y-Less** [comment] 2017-04-25 15:32
OK, well I've managed to at least now reproduce the problem.

**Comment by rt-2** [comment] 2017-04-25 15:36
I used last version of this compiler and last version of YSI.
I have attempted to fix this, tell me if there is something I have not taken into account, but I think that would be the solution?
https://github.com/Misiur/YSI-Includes/pull/171

**Comment by Y-Less** [comment] 2017-04-25 15:41
Unfortunately that's not quite the solution - it won't work for:

```pawn
#include <YSI\y_iterate>
#include <YSI\y_iterate>
#include <foreach>
```

However, I'm working on a more comprehensive solution that will work without modifying the stand-alone versions.

**Comment by Y-Less** [comment] 2017-04-25 15:58
```pawn

// "y_iterate" is always higher than "foreach".
#define _Y_ITERATE_LOCAL_VERSION        42

#if __Pawn != 0x030A
	#define NO_CUSTOM_WARNINGS
#endif

#if !defined _inc_y_iterate
	// The stand-alone version looks for this symbol, even on the new compiler.
	#define _inc_y_iterate
#endif

#if defined NEVER_Y_ITERATE
	// Extra macro so that those paranoid about accidentally including YSI can
	// ensure it never happens.
	#define FOREACH_VERSION _FOREACH_LOCAL_VERSION
	#undef _inc_y_iterate
	#undef _Y_ITERATE_LOCAL_VERSION
	#endinput
#endif

// Foreach is testing us.
#if defined _FOREACH_INC_TEST
	#if !defined _Y_ITERATE_FOUND
		// Set up so that you can use `FOREACH_VERSION` even if the older
		// stand-alone version doesn't support it.
		#define FOREACH_VERSION _FOREACH_LOCAL_VERSION
		#define _FOREACH_CUR_VERSION _Y_ITERATE_LOCAL_VERSION
	#endif
	#endinput
#endif
#if !defined _FOREACH_NO_TEST
	#define _FOREACH_INC_TEST
	// Ignore the broken stand-alone version.
	#define _foreach_included
	#tryinclude <foreach>
	#undef _FOREACH_INC_TEST
	// <foreach> exists - test which is newer.
	#if defined _FOREACH_LOCAL_VERSION
		#if _FOREACH_LOCAL_VERSION > _Y_ITERATE_LOCAL_VERSION
			// Foreach is newer.
			#if defined _inc_foreach
				#undef _inc_foreach
			#endif
			#define _FOREACH_NO_TEST
			#include <foreach>
			#define FOREACH_VERSION _FOREACH_LOCAL_VERSION
			#define _FOREACH_INC_TEST
			#define _Y_ITERATE_FOUND
			#endinput
		#endif
	#elseif defined foreach
		#if __Pawn == 0x030A
			#define WARNING 1
			#include "y_iterate/warning" // Backwards-compatible directive.
			#endinput
		#else
			#error Old foreach.inc files are no longer compatible with YSI.
		#endif
	#endif
#endif
#if defined FOREACH_VERSION
	#undef FOREACH_VERSION
#endif
#define FOREACH_VERSION _Y_ITERATE_LOCAL_VERSION
#define _FOREACH_INC_TEST
#define _Y_ITERATE_FOUND
#if defined _FOREACH_CUR_VERSION
	#undef _FOREACH_CUR_VERSION
#endif

#if !defined _samp_included
	#error "Please include a_samp or a_npc before foreach"
#endif
```

Very complex I know, but this will handle every combination I could think of of old and new versions of `foreach` and `y_iterate` all together.  It also adds `FOREACH_VERSION` - a handy macro to tell you the version you included (with one exception - only https://github.com/Open-GTO/foreach was included), and adds `NEVER_Y_ITERATE` which you can define to ensure that `foreach` NEVER includes YSI, even if it is newer (for the paranoid YSI haters).

**Comment by rt-2** [comment] 2017-04-25 16:13
Just a question, why are you un-defining _FOREACH_CUR_VERSION at the end of the header?

**Comment by Y-Less** [comment] 2017-04-25 16:47
In case someone includes `foreach` after - I can't modify that one to undefine it in the same way you did for this one.

**Comment by Y-Less** [comment] 2017-04-26 10:16
@Zeex could you close this please?

**Comment by Y-Less** [comment] 2017-04-26 12:13
Ahh yeah, forgot the starter could close it as well...

**Closed** 2017-04-26 12:13 UTC
